/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type NavLink = {
  _type: 'navLink'
  label: string
  link: Link
  isPrimary?: boolean
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  buttons?: Array<
    {
      _key: string
    } & Button
  >
  visualMode?: 'none' | 'inline' | 'background'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  mediaLayout?: 'textFirst' | 'imageFirst'
  overlayStrength?: number
  theme?: 'light' | 'dark' | 'accent'
  textAlign?: 'left' | 'center'
  contentWidth?: 'compact' | 'comfortable' | 'wide'
  spacingTop?: 'tight' | 'regular' | 'roomy' | 'pageTop'
  spacingBottom?: 'tight' | 'regular' | 'roomy'
}

export type Testimonial = {
  _type: 'testimonial'
  quote: string
  author: string
  role?: string
  avatar?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark' | 'tint'
  textAlign?: 'left' | 'center'
  showDivider?: boolean
  spacingTop?: 'tight' | 'regular' | 'roomy'
  spacingBottom?: 'tight' | 'regular' | 'roomy'
}

export type InfoSection = {
  _type: 'infoSection'
  heading: string
  subheading?: string
  content: BlockContent
  theme?: 'light' | 'tint' | 'ink'
  textAlign?: 'left' | 'center'
  measure?: 'compact' | 'comfortable' | 'wide' | 'auto'
  showDivider?: boolean
  spacingTop?: 'tight' | 'regular' | 'roomy'
  spacingBottom?: 'tight' | 'regular' | 'roomy'
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText: string
  style?: 'auto' | 'primary' | 'secondary' | 'ghost'
  link: Link
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  links?: Array<
    {
      _key: string
    } & NavLink
  >
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & Testimonial)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  colorPreset?: 'teal' | 'purple' | 'green' | 'orange'
  headerStyle?: 'minimal' | 'boxed'
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | NavLink
  | PageReference
  | PostReference
  | Link
  | SanityImageAssetReference
  | CallToAction
  | Testimonial
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Navigation
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | PersonReference
  | Post
  | Person
  | Slug
  | Settings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  colorPreset?: 'green' | 'orange' | 'purple' | 'teal'
  headerStyle?: 'boxed' | 'minimal'
} | null

// Source: sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{title, links[]{..., link{..., "page": page->slug.current, "post": post->slug.current}}}
export type NavigationQueryResult = {
  title: string | null
  links: Array<{
    _key: string
    _type: 'navLink'
    label: string
    link: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    }
    isPrimary?: boolean
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{        _type == "callToAction" => {    ...,    buttons[]{        _type == "button" => {    _key,    _type,    buttonText,    style,    link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  }    }  },  _type == "infoSection" => {    ...,    content[]{      ...,      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "testimonial" => {    ...  },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        buttons: Array<{
          _key: string
          _type: 'button'
          buttonText: string
          style: 'auto' | 'ghost' | 'primary' | 'secondary' | null
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          }
        }> | null
        visualMode?: 'background' | 'inline' | 'none'
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        mediaLayout?: 'imageFirst' | 'textFirst'
        overlayStrength?: number
        theme?: 'accent' | 'dark' | 'light'
        textAlign?: 'center' | 'left'
        contentWidth?: 'comfortable' | 'compact' | 'wide'
        spacingTop?: 'pageTop' | 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        >
        theme?: 'ink' | 'light' | 'tint'
        textAlign?: 'center' | 'left'
        measure?: 'auto' | 'comfortable' | 'compact' | 'wide'
        showDivider?: boolean
        spacingTop?: 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
    | {
        _key: string
        _type: 'testimonial'
        quote: string
        author: string
        role?: string
        avatar?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light' | 'tint'
        textAlign?: 'center' | 'left'
        showDivider?: boolean
        spacingTop?: 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getHomePageQuery
// Query: *[_type == 'page' && slug.current == "home"][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{        _type == "callToAction" => {    ...,    buttons[]{        _type == "button" => {    _key,    _type,    buttonText,    style,    link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  }    }  },  _type == "infoSection" => {    ...,    content[]{      ...,      markDefs[]{        ...,          _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }    }  },  _type == "testimonial" => {    ...  },    },  }
export type GetHomePageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        buttons: Array<{
          _key: string
          _type: 'button'
          buttonText: string
          style: 'auto' | 'ghost' | 'primary' | 'secondary' | null
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          }
        }> | null
        visualMode?: 'background' | 'inline' | 'none'
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        mediaLayout?: 'imageFirst' | 'textFirst'
        overlayStrength?: number
        theme?: 'accent' | 'dark' | 'light'
        textAlign?: 'center' | 'left'
        contentWidth?: 'comfortable' | 'compact' | 'wide'
        spacingTop?: 'pageTop' | 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        >
        theme?: 'ink' | 'light' | 'tint'
        textAlign?: 'center' | 'left'
        measure?: 'auto' | 'comfortable' | 'compact' | 'wide'
        showDivider?: boolean
        spacingTop?: 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
    | {
        _key: string
        _type: 'testimonial'
        quote: string
        author: string
        role?: string
        avatar?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light' | 'tint'
        textAlign?: 'center' | 'left'
        showDivider?: boolean
        spacingTop?: 'regular' | 'roomy' | 'tight'
        spacingBottom?: 'regular' | 'roomy' | 'tight'
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '*[_type == "navigation"][0]{title, links[]{..., link{..., "page": page->slug.current, "post": post->slug.current}}}': NavigationQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      \n  _type == "callToAction" => {\n    ...,\n    buttons[]{\n      \n  _type == "button" => {\n    _key,\n    _type,\n    buttonText,\n    style,\n    link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  }\n\n    }\n  },\n  _type == "infoSection" => {\n    ...,\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n    }\n  },\n  _type == "testimonial" => {\n    ...\n  },\n\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == \'page\' && slug.current == "home"][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      \n  _type == "callToAction" => {\n    ...,\n    buttons[]{\n      \n  _type == "button" => {\n    _key,\n    _type,\n    buttonText,\n    style,\n    link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  }\n\n    }\n  },\n  _type == "infoSection" => {\n    ...,\n    content[]{\n      ...,\n      markDefs[]{\n        ...,\n        \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n    }\n  },\n  _type == "testimonial" => {\n    ...\n  },\n\n    },\n  }\n': GetHomePageQueryResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
  }
}
